apiVersion: 1

deleteDatasources:
  - name: LOCAL_INFLUX
    orgId: 1

datasources:
  - name: LOCAL_INFLUX
    type: influxdb
    access: proxy
    uid: cevyn8xwabcw0d
    url: http://influxdb:8086
    password:
    user:
    
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: false
    jsonData:
      dbName: k6
      tlsAuth: false
      tlsAuthWithCACert: false
      pdcInjected: false
    secureJsonData:
      tlsCACert: ""
      tlsClientCert: ""
      tlsClientKey: ""
    version: 1
    editable: true
