global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: "my-project"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]
    #scheme: http

    #static_configs:
      # - targets: ["cadvisor:8080", "node-exporter:9100", "nginx-exporter:9113"]
  - job_name: ".Net"
    scrape_interval: 10s
    scheme: http
    static_configs:
      - targets: ["switchApi:8080"]

  - job_name: "k6"
    scrape_interval: 10s
    scheme: http
    static_configs:
      - targets: ["k6:6565"]
    metrics_path: /metrics
